services:
  jenkins:
    image: 'zazathomas/jenkins-blueocean:2.468'
    container_name: jenkins-blueocean
    restart: unless-stopped
    environment:
      DOCKER_HOST: 'tcp://docker:2376'
      DOCKER_CERT_PATH: '/certs/client'
      DOCKER_TLS_VERIFY: 1
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client:ro
    networks:
     - jenkins
networks:
  jenkins:
    name: jenkins
    external: true
